# Generated by Django 4.2.4 on 2024-07-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.CharField(default='0000000', max_length=255),
        ),
    ]
